project:
  type: website

website:
  title: Quantitative Methods and Statistics
  sidebar:
  # - title: "Quantitative Methods and Statistics"
    # style: "docked"
    # search: true
    contents:
      - contents:
        text: "Course introduction"
        href: "index.qmd"
      - section: "Basics of `R` programming"
        contents:
        - text: "Introduction to `R`"
          href: "01-introduction.qmd"
        - text: "Data wrangling"
          href: "02-data-wrangling.qmd"
      - section: "Describing data"
        contents:
        - text: "Data visualization"
          href: "03-data-visualization.qmd"
        - text: "Univariate descriptions"
          href: "04-descriptive-univariate.qmd"
        - text: "Multivariate descriptions"
          href: "05-descriptive-multivariate.qmd"
      - section: "Statistical modeling"
        contents:
        - text: "Model building"
          href: "06-statistical-models.qmd"
        - text: "Bayesian inference"
          href: "07-globe-tossing.qmd"
        - text: "Linear regression"
          href: "08-linear-regression.qmd"
      - section: "Causal inference"
        contents:
        - text: "Experiments"
          href: "09-experiments.qmd"
        - text: "Observational studies"
          href: "10-observational-studies.qmd"
      - section: "Advanced modeling"
        contents:
        - text: "Generalized linear models"
          href: "11-generalized-linear-models.qmd"
        - text: "Generalized additive models"
          href: "12-generalized-additive-models.qmd"
        - text: "Multilevel models"
          href: "13-multilevel-models.qmd"
      - section: "Case studies"
        contents:
        - text: "Making a map from Eurostat data"
          href: "casestudy-eurostat.qmd"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
